use std::{env, fs, path::PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=rules/managed.rules");
    if env::var("CARGO_CFG_TARGET_ARCH").as_deref() == Ok("wasm32") {
        println!("cargo:rustc-link-arg=--export-memory");
        println!("cargo:rustc-link-arg=--max-memory=16777216");
    }
    let source = fs::read_to_string("rules/managed.rules").expect("read managed WAF rules");
    let mut rules = Vec::new();
    for (line_number, line) in source.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<_> = line.split('|').collect();
        assert_eq!(fields.len(), 3, "managed rule line {}", line_number + 1);
        assert!(
            fields.iter().all(|value| value.is_ascii()),
            "managed rules must be ASCII"
        );
        rules.push((
            fields[0].to_owned(),
            fields[1].to_owned(),
            fields[2].to_ascii_lowercase(),
        ));
    }
    rules.sort();
    let mut generated = String::from(
        "// @generated by plugins/waf/build.rs; deterministic managed rule bytecode.\n",
    );
    generated.push_str("pub(crate) static MANAGED_RULES: &[ManagedRule] = &[\n");
    for (id, target, needle) in rules {
        generated.push_str(&format!(
            "    ManagedRule {{ id: {:?}, target: Target::{}, needle: {:?}.as_bytes() }},\n",
            id, target, needle
        ));
    }
    generated.push_str("];\n");
    let output = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR")).join("managed_rules.rs");
    fs::write(output, generated).expect("write managed WAF bytecode");
}
