// Code generated by internal/ci/sdk from canonical public pluginsdk and protoschema; DO NOT EDIT.

pub const CANONICAL_DESCRIPTOR_SET_SHA256: &str =
    "5cbab7e002914f3da5e80a762594c2b61fe8c44b7f320146e70d6789c3c6cd86";
pub const POLICY_ABI_V1: &str = "nre:policy/v1";
pub const ABI_MAJOR_VERSION: u32 = 1;

pub const EXPORT_VERSION: &str = "nre_policy_version";
pub const EXPORT_ALLOCATE: &str = "nre_policy_alloc";
pub const EXPORT_FREE: &str = "nre_policy_free";
pub const EXPORT_INIT: &str = "nre_policy_init";
pub const EXPORT_EVALUATE: &str = "nre_policy_evaluate";
pub const EXPORT_RESET: &str = "nre_policy_reset";
pub const EXPORT_MEMORY: &str = "memory";

pub const HOST_MODULE: &str = "nre:policy/v1";
pub const HOST_READ_FIELD: &str = "nre_host_read_field";
pub const HOST_READ_BODY_WINDOW: &str = "nre_host_read_body_window";
pub const HOST_STATE_GET: &str = "nre_host_state_get";
pub const HOST_STATE_PUT: &str = "nre_host_state_put";
pub const HOST_EMIT_EVENT: &str = "nre_host_emit_event";
pub const HOST_ADD_METRIC: &str = "nre_host_add_metric";

pub const MAX_TIMEOUT_MILLISECONDS: u32 = 2;
pub const MIN_MEMORY_BYTES: u64 = 65536;
pub const MAX_MEMORY_BYTES: u64 = 16777216;
pub const MAX_CONCURRENCY: u32 = 64;
pub const MIN_INPUT_FRAME_BYTES: usize = 6;
pub const MAX_INPUT_FRAME_BYTES: usize = 131072;
pub const MIN_OUTPUT_FRAME_BYTES: usize = 4;
pub const MAX_OUTPUT_FRAME_BYTES: usize = 4096;

pub const BUDGET_INPUT: &str = "input";
pub const BUDGET_OUTPUT: &str = "output";
pub const BUDGET_MEMORY: &str = "memory";
pub const BUDGET_CONCURRENCY: &str = "concurrency";
pub const BUDGET_DEADLINE: &str = "deadline";
pub const BUDGET_STATE: &str = "state";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum AbiStatus {
    Ok = 0,
    InvalidArgument = 1,
    PermissionDenied = 2,
    ResourceExhausted = 3,
    DeadlineExceeded = 4,
    Unavailable = 5,
    IncompatibleAbi = 6,
    Internal = 7,
}

impl AbiStatus {
    pub const fn from_u32(value: u32) -> Option<Self> {
        match value {
            0 => Some(Self::Ok),
            1 => Some(Self::InvalidArgument),
            2 => Some(Self::PermissionDenied),
            3 => Some(Self::ResourceExhausted),
            4 => Some(Self::DeadlineExceeded),
            5 => Some(Self::Unavailable),
            6 => Some(Self::IncompatibleAbi),
            7 => Some(Self::Internal),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum RuntimeErrorCode {
    Unspecified = 0,
    InvalidArgument = 1,
    PermissionDenied = 2,
    ResourceExhausted = 3,
    DeadlineExceeded = 4,
    Unavailable = 5,
    IncompatibleAbi = 6,
    Internal = 7,
}

impl RuntimeErrorCode {
    pub const fn from_u32(value: u32) -> Option<Self> {
        match value {
            0 => Some(Self::Unspecified),
            1 => Some(Self::InvalidArgument),
            2 => Some(Self::PermissionDenied),
            3 => Some(Self::ResourceExhausted),
            4 => Some(Self::DeadlineExceeded),
            5 => Some(Self::Unavailable),
            6 => Some(Self::IncompatibleAbi),
            7 => Some(Self::Internal),
            _ => None,
        }
    }
}

impl RuntimeErrorCode {
    pub const fn is_failure(self) -> bool {
        !matches!(self, Self::Unspecified)
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum PolicyAction {
    Unspecified = 0,
    Allow = 1,
    Deny = 2,
    Observe = 3,
}

impl PolicyAction {
    pub const fn from_u32(value: u32) -> Option<Self> {
        match value {
            0 => Some(Self::Unspecified),
            1 => Some(Self::Allow),
            2 => Some(Self::Deny),
            3 => Some(Self::Observe),
            _ => None,
        }
    }
}

impl PolicyAction {
    pub const fn is_decision(self) -> bool {
        !matches!(self, Self::Unspecified)
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum SecurityEventCode {
    Unspecified = 0,
    WafRuleMatch = 1,
}

impl SecurityEventCode {
    pub const fn from_u32(value: u32) -> Option<Self> {
        match value {
            0 => Some(Self::Unspecified),
            1 => Some(Self::WafRuleMatch),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum SecurityEventAction {
    Unspecified = 0,
    Observe = 1,
    Deny = 2,
}

impl SecurityEventAction {
    pub const fn from_u32(value: u32) -> Option<Self> {
        match value {
            0 => Some(Self::Unspecified),
            1 => Some(Self::Observe),
            2 => Some(Self::Deny),
            _ => None,
        }
    }
}

pub mod field {
    pub mod init_request {
        pub const CONFIG: u32 = 1;
        pub const GRANTED_SCOPES: u32 = 2;
        pub const GENERATION: u32 = 3;
    }
    pub mod evaluate_request {
        pub const EXTENSION_POINT: u32 = 1;
        pub const REQUEST_ID: u32 = 2;
        pub const PAYLOAD: u32 = 3;
    }
    pub mod evaluate_response {
        pub const SUCCESS: u32 = 1;
        pub const ERROR: u32 = 2;
    }
    pub mod evaluate_success {
        pub const ACTION: u32 = 1;
        pub const PAYLOAD: u32 = 2;
    }
    pub mod runtime_error {
        pub const CODE: u32 = 1;
        pub const MESSAGE: u32 = 2;
        pub const RETRYABLE: u32 = 3;
    }
    pub mod read_field_request {
        pub const NAME: u32 = 1;
    }
    pub mod read_body_window_request {
        pub const OFFSET: u32 = 1;
        pub const LENGTH: u32 = 2;
    }
    pub mod state_get_request {
        pub const KEY: u32 = 1;
    }
    pub mod state_put_request {
        pub const KEY: u32 = 1;
        pub const VALUE: u32 = 2;
    }
    pub mod emit_event_request {
        pub const CODE: u32 = 1;
        pub const ACTION: u32 = 2;
    }
    pub mod add_metric_request {
        pub const NAME: u32 = 1;
        pub const DELTA: u32 = 2;
    }
    pub mod bytes_response {
        pub const VALUE: u32 = 1;
        pub const FOUND: u32 = 2;
    }
}

#[cfg(target_arch = "wasm32")]
#[link(wasm_import_module = "nre:policy/v1")]
unsafe extern "C" {
    pub(crate) fn nre_host_read_field(
        request_ptr: u32,
        request_len: u32,
        response_ptr: u32,
        response_capacity: u32,
    ) -> u64;
    pub(crate) fn nre_host_read_body_window(
        request_ptr: u32,
        request_len: u32,
        response_ptr: u32,
        response_capacity: u32,
    ) -> u64;
    pub(crate) fn nre_host_state_get(
        request_ptr: u32,
        request_len: u32,
        response_ptr: u32,
        response_capacity: u32,
    ) -> u64;
    pub(crate) fn nre_host_state_put(
        request_ptr: u32,
        request_len: u32,
        response_ptr: u32,
        response_capacity: u32,
    ) -> u64;
    pub(crate) fn nre_host_emit_event(
        request_ptr: u32,
        request_len: u32,
        response_ptr: u32,
        response_capacity: u32,
    ) -> u64;
    pub(crate) fn nre_host_add_metric(
        request_ptr: u32,
        request_len: u32,
        response_ptr: u32,
        response_capacity: u32,
    ) -> u64;
}
