// Code generated by internal/ci/sdk from canonical public pluginsdk and protoschema; DO NOT EDIT.

pub const CANONICAL_DESCRIPTOR_SET_SHA256: &str =
    "2abec011209434be336af2a245d10268c891914aa6f12b60c8eea2d71a8d5170";
pub const POLICY_ABI_V1: &str = "nre:policy/v1";
pub const ABI_MAJOR_VERSION: u32 = 1;

pub const EXPORT_VERSION: &str = "nre_policy_version";
pub const EXPORT_ALLOCATE: &str = "nre_policy_alloc";
pub const EXPORT_FREE: &str = "nre_policy_free";
pub const EXPORT_INIT: &str = "nre_policy_init";
pub const EXPORT_EVALUATE: &str = "nre_policy_evaluate";
pub const EXPORT_RESET: &str = "nre_policy_reset";
pub const EXPORT_MEMORY: &str = "memory";

pub const HOST_MODULE: &str = "nre:policy/v1";
pub const HOST_READ_FIELD: &str = "nre_host_read_field";
pub const HOST_READ_NORMALIZED_HTTP: &str = "nre_host_read_normalized_http";
pub const HOST_READ_BODY_WINDOW: &str = "nre_host_read_body_window";
pub const HOST_STATE_GET: &str = "nre_host_state_get";
pub const HOST_STATE_PUT: &str = "nre_host_state_put";
pub const HOST_EMIT_EVENT: &str = "nre_host_emit_event";
pub const HOST_ADD_METRIC: &str = "nre_host_add_metric";
pub const HOST_READ_TRUSTED_SOURCE: &str = "nre_host_read_trusted_source";
pub const HOST_DATASET_QUERY: &str = "nre_host_dataset_query";
pub const HOST_DATASET_RESOLVE: &str = "nre_host_dataset_resolve";

pub const MAX_TIMEOUT_MILLISECONDS: u32 = 2;
pub const MIN_MEMORY_BYTES: u64 = 65536;
pub const MAX_MEMORY_BYTES: u64 = 16777216;
pub const MAX_CONCURRENCY: u32 = 64;
pub const MIN_INPUT_FRAME_BYTES: usize = 6;
pub const MAX_INPUT_FRAME_BYTES: usize = 131072;
pub const MIN_OUTPUT_FRAME_BYTES: usize = 4;
pub const MAX_OUTPUT_FRAME_BYTES: usize = 4096;

pub const BUDGET_INPUT: &str = "input";
pub const BUDGET_OUTPUT: &str = "output";
pub const BUDGET_MEMORY: &str = "memory";
pub const BUDGET_CONCURRENCY: &str = "concurrency";
pub const BUDGET_DEADLINE: &str = "deadline";
pub const BUDGET_STATE: &str = "state";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum AbiStatus {
    Ok = 0,
    InvalidArgument = 1,
    PermissionDenied = 2,
    ResourceExhausted = 3,
    DeadlineExceeded = 4,
    Unavailable = 5,
    IncompatibleAbi = 6,
    Internal = 7,
}

impl AbiStatus {
    pub const fn from_u32(value: u32) -> Option<Self> {
        match value {
            0 => Some(Self::Ok),
            1 => Some(Self::InvalidArgument),
            2 => Some(Self::PermissionDenied),
            3 => Some(Self::ResourceExhausted),
            4 => Some(Self::DeadlineExceeded),
            5 => Some(Self::Unavailable),
            6 => Some(Self::IncompatibleAbi),
            7 => Some(Self::Internal),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum RuntimeErrorCode {
    Unspecified = 0,
    InvalidArgument = 1,
    PermissionDenied = 2,
    ResourceExhausted = 3,
    DeadlineExceeded = 4,
    Unavailable = 5,
    IncompatibleAbi = 6,
    Internal = 7,
}

impl RuntimeErrorCode {
    pub const fn from_u32(value: u32) -> Option<Self> {
        match value {
            0 => Some(Self::Unspecified),
            1 => Some(Self::InvalidArgument),
            2 => Some(Self::PermissionDenied),
            3 => Some(Self::ResourceExhausted),
            4 => Some(Self::DeadlineExceeded),
            5 => Some(Self::Unavailable),
            6 => Some(Self::IncompatibleAbi),
            7 => Some(Self::Internal),
            _ => None,
        }
    }
}

impl RuntimeErrorCode {
    pub const fn is_failure(self) -> bool {
        !matches!(self, Self::Unspecified)
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum PolicyAction {
    Unspecified = 0,
    Allow = 1,
    Deny = 2,
    Observe = 3,
}

impl PolicyAction {
    pub const fn from_u32(value: u32) -> Option<Self> {
        match value {
            0 => Some(Self::Unspecified),
            1 => Some(Self::Allow),
            2 => Some(Self::Deny),
            3 => Some(Self::Observe),
            _ => None,
        }
    }
}

impl PolicyAction {
    pub const fn is_decision(self) -> bool {
        !matches!(self, Self::Unspecified)
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum SecurityEventCode {
    Unspecified = 0,
    WafRuleMatch = 1,
    IpRuleMatch = 2,
    IpCheckFailure = 3,
    RoutingRuleMatch = 4,
    RoutingFailure = 5,
}

impl SecurityEventCode {
    pub const fn from_u32(value: u32) -> Option<Self> {
        match value {
            0 => Some(Self::Unspecified),
            1 => Some(Self::WafRuleMatch),
            2 => Some(Self::IpRuleMatch),
            3 => Some(Self::IpCheckFailure),
            4 => Some(Self::RoutingRuleMatch),
            5 => Some(Self::RoutingFailure),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum SecurityEventAction {
    Unspecified = 0,
    Observe = 1,
    Deny = 2,
    Allow = 3,
    Direct = 4,
    Upstream = 5,
}

impl SecurityEventAction {
    pub const fn from_u32(value: u32) -> Option<Self> {
        match value {
            0 => Some(Self::Unspecified),
            1 => Some(Self::Observe),
            2 => Some(Self::Deny),
            3 => Some(Self::Allow),
            4 => Some(Self::Direct),
            5 => Some(Self::Upstream),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum SecurityEventReason {
    None = 0,
    SourceUnauthenticated = 1,
    DatasetUnavailable = 2,
    ClassificationMissing = 3,
    BudgetExceeded = 4,
    UpstreamUnavailable = 5,
    UpstreamAuthentication = 6,
    ProtocolUnsupported = 7,
    DataInvalid = 8,
    CoverageUnknown = 9,
    Revoked = 10,
}

impl SecurityEventReason {
    pub const fn from_u32(value: u32) -> Option<Self> {
        match value {
            0 => Some(Self::None),
            1 => Some(Self::SourceUnauthenticated),
            2 => Some(Self::DatasetUnavailable),
            3 => Some(Self::ClassificationMissing),
            4 => Some(Self::BudgetExceeded),
            5 => Some(Self::UpstreamUnavailable),
            6 => Some(Self::UpstreamAuthentication),
            7 => Some(Self::ProtocolUnsupported),
            8 => Some(Self::DataInvalid),
            9 => Some(Self::CoverageUnknown),
            10 => Some(Self::Revoked),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum PolicyDomainSource {
    Unspecified = 0,
    Original = 1,
    HttpHost = 2,
    TlsSni = 3,
    IpOnly = 4,
    Unavailable = 5,
}

impl PolicyDomainSource {
    pub const fn from_u32(value: u32) -> Option<Self> {
        match value {
            0 => Some(Self::Unspecified),
            1 => Some(Self::Original),
            2 => Some(Self::HttpHost),
            3 => Some(Self::TlsSni),
            4 => Some(Self::IpOnly),
            5 => Some(Self::Unavailable),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum TrustedSourceAuthority {
    Unspecified = 0,
    Socket = 1,
    Xff = 2,
    Proxy = 3,
    Relay = 4,
}

impl TrustedSourceAuthority {
    pub const fn from_u32(value: u32) -> Option<Self> {
        match value {
            0 => Some(Self::Unspecified),
            1 => Some(Self::Socket),
            2 => Some(Self::Xff),
            3 => Some(Self::Proxy),
            4 => Some(Self::Relay),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum DatasetClassificationKind {
    Unspecified = 0,
    Country = 1,
    Region = 2,
    Cidr = 3,
}

impl DatasetClassificationKind {
    pub const fn from_u32(value: u32) -> Option<Self> {
        match value {
            0 => Some(Self::Unspecified),
            1 => Some(Self::Country),
            2 => Some(Self::Region),
            3 => Some(Self::Cidr),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum DatasetMatchCoverage {
    Unspecified = 0,
    Covered = 1,
    Unknown = 2,
    UnsupportedFamily = 3,
}

impl DatasetMatchCoverage {
    pub const fn from_u32(value: u32) -> Option<Self> {
        match value {
            0 => Some(Self::Unspecified),
            1 => Some(Self::Covered),
            2 => Some(Self::Unknown),
            3 => Some(Self::UnsupportedFamily),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum DatasetQueryStatus {
    Unspecified = 0,
    Ok = 1,
    Unavailable = 2,
    MissingClassification = 3,
    BudgetExceeded = 4,
    Unauthorized = 5,
    StaleReference = 6,
    InvalidData = 7,
}

impl DatasetQueryStatus {
    pub const fn from_u32(value: u32) -> Option<Self> {
        match value {
            0 => Some(Self::Unspecified),
            1 => Some(Self::Ok),
            2 => Some(Self::Unavailable),
            3 => Some(Self::MissingClassification),
            4 => Some(Self::BudgetExceeded),
            5 => Some(Self::Unauthorized),
            6 => Some(Self::StaleReference),
            7 => Some(Self::InvalidData),
            _ => None,
        }
    }
}

pub mod field {
    pub mod init_request {
        pub const CONFIG: u32 = 1;
        pub const GRANTED_SCOPES: u32 = 2;
        pub const GENERATION: u32 = 3;
    }
    pub mod evaluate_request {
        pub const EXTENSION_POINT: u32 = 1;
        pub const REQUEST_ID: u32 = 2;
        pub const PAYLOAD: u32 = 3;
        pub const NORMALIZED_HTTP: u32 = 4;
    }
    pub mod evaluate_response {
        pub const SUCCESS: u32 = 1;
        pub const ERROR: u32 = 2;
    }
    pub mod evaluate_success {
        pub const ACTION: u32 = 1;
        pub const PAYLOAD: u32 = 2;
    }
    pub mod runtime_error {
        pub const CODE: u32 = 1;
        pub const MESSAGE: u32 = 2;
        pub const RETRYABLE: u32 = 3;
    }
    pub mod read_field_request {
        pub const NAME: u32 = 1;
    }
    pub mod read_normalized_http_request {}
    pub mod normalized_http_response {
        pub const PATH: u32 = 1;
        pub const QUERY: u32 = 2;
        pub const HEADERS: u32 = 3;
        pub const TRUSTED_SOURCE: u32 = 4;
        pub const TRUSTED_SOURCE_AUTHENTICATED: u32 = 5;
        pub const BODY_WINDOW_COMPLETE: u32 = 6;
        pub const BODY_WINDOW_LENGTH: u32 = 7;
    }
    pub mod read_body_window_request {
        pub const OFFSET: u32 = 1;
        pub const LENGTH: u32 = 2;
    }
    pub mod state_get_request {
        pub const KEY: u32 = 1;
    }
    pub mod state_put_request {
        pub const KEY: u32 = 1;
        pub const VALUE: u32 = 2;
    }
    pub mod emit_event_request {
        pub const CODE: u32 = 1;
        pub const ACTION: u32 = 2;
        pub const RULE_INDEX: u32 = 3;
        pub const DATASET_INDEX: u32 = 4;
        pub const CLASSIFICATION_INDEX: u32 = 5;
        pub const OUTBOUND_INDEX: u32 = 6;
        pub const REASON: u32 = 7;
        pub const DOMAIN_SOURCE: u32 = 8;
    }
    pub mod add_metric_request {
        pub const NAME: u32 = 1;
        pub const DELTA: u32 = 2;
    }
    pub mod bytes_response {
        pub const VALUE: u32 = 1;
        pub const FOUND: u32 = 2;
    }
    pub mod read_trusted_source_request {}
    pub mod trusted_source {
        pub const INSTANCE_ID: u32 = 1;
        pub const GENERATION: u32 = 2;
        pub const ENTRY_ID: u32 = 3;
        pub const PEER_ADDRESS: u32 = 4;
        pub const SOURCE_ADDRESS: u32 = 5;
        pub const AUTHORITY: u32 = 6;
    }
    pub mod trusted_source_response {
        pub const SOURCE: u32 = 1;
        pub const ERROR: u32 = 2;
    }
    pub mod dataset_reference {
        pub const HANDLE: u32 = 1;
        pub const INSTANCE_ID: u32 = 2;
        pub const GENERATION: u32 = 3;
        pub const SOURCE_ID: u32 = 4;
        pub const VERSION_DIGEST: u32 = 5;
    }
    pub mod dataset_resolve_request {
        pub const SOURCE_ID: u32 = 1;
        pub const MAX_DURATION_MICROS: u32 = 2;
        pub const MAX_RESPONSE_BYTES: u32 = 3;
    }
    pub mod dataset_resolve_response {
        pub const REFERENCE: u32 = 1;
        pub const ERROR: u32 = 2;
    }
    pub mod dataset_classification {
        pub const NAME: u32 = 1;
        pub const KIND: u32 = 2;
    }
    pub mod dataset_query_request {
        pub const REFERENCE: u32 = 1;
        pub const CLASSIFICATIONS: u32 = 2;
        pub const MAX_DURATION_MICROS: u32 = 3;
        pub const MAX_RESPONSE_BYTES: u32 = 4;
    }
    pub mod dataset_match {
        pub const INDEX: u32 = 1;
        pub const MATCHED: u32 = 2;
        pub const COVERAGE: u32 = 3;
    }
    pub mod dataset_query_response {
        pub const REFERENCE: u32 = 1;
        pub const STATUS: u32 = 2;
        pub const MATCHES: u32 = 3;
    }
}

#[cfg(target_arch = "wasm32")]
#[link(wasm_import_module = "nre:policy/v1")]
unsafe extern "C" {
    pub(crate) fn nre_host_read_field(
        request_ptr: u32,
        request_len: u32,
        response_ptr: u32,
        response_capacity: u32,
    ) -> u64;
    pub(crate) fn nre_host_read_normalized_http(
        request_ptr: u32,
        request_len: u32,
        response_ptr: u32,
        response_capacity: u32,
    ) -> u64;
    pub(crate) fn nre_host_read_body_window(
        request_ptr: u32,
        request_len: u32,
        response_ptr: u32,
        response_capacity: u32,
    ) -> u64;
    pub(crate) fn nre_host_state_get(
        request_ptr: u32,
        request_len: u32,
        response_ptr: u32,
        response_capacity: u32,
    ) -> u64;
    pub(crate) fn nre_host_state_put(
        request_ptr: u32,
        request_len: u32,
        response_ptr: u32,
        response_capacity: u32,
    ) -> u64;
    pub(crate) fn nre_host_emit_event(
        request_ptr: u32,
        request_len: u32,
        response_ptr: u32,
        response_capacity: u32,
    ) -> u64;
    pub(crate) fn nre_host_add_metric(
        request_ptr: u32,
        request_len: u32,
        response_ptr: u32,
        response_capacity: u32,
    ) -> u64;
    pub(crate) fn nre_host_read_trusted_source(
        request_ptr: u32,
        request_len: u32,
        response_ptr: u32,
        response_capacity: u32,
    ) -> u64;
    pub(crate) fn nre_host_dataset_query(
        request_ptr: u32,
        request_len: u32,
        response_ptr: u32,
        response_capacity: u32,
    ) -> u64;
    pub(crate) fn nre_host_dataset_resolve(
        request_ptr: u32,
        request_len: u32,
        response_ptr: u32,
        response_capacity: u32,
    ) -> u64;
}
